// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230630200531_AddInventory")]
    partial class AddInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Modules.Addresses.Contract.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Backend.Modules.Cities.Contract.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca5e9b9c-05c3-4e95-83c2-eca36aad8500"),
                            Name = "Фурманов"
                        },
                        new
                        {
                            Id = new Guid("219a2ce6-d598-4067-925c-03eb345b1a76"),
                            Name = "Владимир"
                        },
                        new
                        {
                            Id = new Guid("49c95aa3-c980-4352-9230-683f28a727ed"),
                            Name = "Приволжск"
                        },
                        new
                        {
                            Id = new Guid("ba1d50cb-74a8-4ae0-88e1-01c8a6e87618"),
                            Name = "Иваново"
                        });
                });

            modelBuilder.Entity("Backend.Modules.Clients.Contract.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatLink")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Backend.Modules.Inventories.Contract.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Backend.Modules.MovementItems.Contract.MovementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("MovementItems");
                });

            modelBuilder.Entity("Backend.Modules.MovementStatuses.Contract.MovementStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MovementStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bec9a5a-ed58-487b-a488-a641e3c601cb"),
                            Name = "Обрабатывается"
                        },
                        new
                        {
                            Id = new Guid("c1c5868a-b7fc-4c58-a8a3-b73b47e2fb9e"),
                            Name = "Доставляется"
                        },
                        new
                        {
                            Id = new Guid("59f8dbbf-c17c-4f25-9e70-8760210422df"),
                            Name = "Ожидает получения"
                        },
                        new
                        {
                            Id = new Guid("0ba48b38-b268-41a5-b228-f8a93590f5d5"),
                            Name = "Выполнен"
                        },
                        new
                        {
                            Id = new Guid("d50d7272-05ca-4e4f-9769-475a7984be77"),
                            Name = "Отменён"
                        });
                });

            modelBuilder.Entity("Backend.Modules.Orders.Contract.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SelectedAddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SelectedAddressId");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Backend.Modules.PriceChanges.Contract.PriceChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangeTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("PriceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PriceTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceChanges");
                });

            modelBuilder.Entity("Backend.Modules.PriceTypes.Contract.PriceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PriceTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3165c0b3-f92f-4a2d-8278-d131b8a32478"),
                            Name = "Опт"
                        },
                        new
                        {
                            Id = new Guid("0d501699-abaf-42ad-a858-eaacc5c50199"),
                            Name = "Розница"
                        });
                });

            modelBuilder.Entity("Backend.Modules.ProductCategories.Contract.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57902a45-c181-4450-ad49-cdaed2faef01"),
                            Name = "Молочные"
                        },
                        new
                        {
                            Id = new Guid("9b52555d-9bb2-4913-9ca8-b8503d21304b"),
                            Name = "Горькие"
                        },
                        new
                        {
                            Id = new Guid("96e0ebf5-b331-4ec1-8993-ce84c0306a0a"),
                            Name = "Белые"
                        },
                        new
                        {
                            Id = new Guid("7b5afc77-f10a-4ea9-bd03-b7ae67e83ea2"),
                            Name = "Фирменные"
                        },
                        new
                        {
                            Id = new Guid("7eb7cdcd-6bb7-46c1-ae35-3b78d51ea2b3"),
                            Name = "Мармелады"
                        },
                        new
                        {
                            Id = new Guid("20cdd5da-445d-4361-83b1-19cfef0542ba"),
                            Name = "Конфеты"
                        },
                        new
                        {
                            Id = new Guid("40c2b950-5e3f-45aa-8e7a-20d6693b250c"),
                            Name = "Пасты"
                        });
                });

            modelBuilder.Entity("Backend.Modules.Products.Contract.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsByWeight")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetailPrice")
                        .HasColumnType("integer");

                    b.Property<int>("VkMarketId")
                        .HasColumnType("integer");

                    b.Property<int>("WholesalePrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Backend.Modules.Shipments.Contract.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Backend.Modules.Addresses.Contract.Address", b =>
                {
                    b.HasOne("Backend.Modules.Cities.Contract.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Modules.Clients.Contract.Client", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Backend.Modules.MovementItems.Contract.MovementItem", b =>
                {
                    b.HasOne("Backend.Modules.Inventories.Contract.Inventory", null)
                        .WithMany("Items")
                        .HasForeignKey("InventoryId");

                    b.HasOne("Backend.Modules.Orders.Contract.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("Backend.Modules.Products.Contract.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Modules.Shipments.Contract.Shipment", null)
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Modules.Orders.Contract.Order", b =>
                {
                    b.HasOne("Backend.Modules.Clients.Contract.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Modules.Addresses.Contract.Address", "SelectedAddress")
                        .WithMany()
                        .HasForeignKey("SelectedAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Modules.MovementStatuses.Contract.MovementStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SelectedAddress");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Backend.Modules.PriceChanges.Contract.PriceChange", b =>
                {
                    b.HasOne("Backend.Modules.PriceTypes.Contract.PriceType", "PriceType")
                        .WithMany()
                        .HasForeignKey("PriceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Modules.Products.Contract.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Modules.Products.Contract.Product", b =>
                {
                    b.HasOne("Backend.Modules.ProductCategories.Contract.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Modules.Shipments.Contract.Shipment", b =>
                {
                    b.HasOne("Backend.Modules.MovementStatuses.Contract.MovementStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Backend.Modules.Clients.Contract.Client", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Backend.Modules.Inventories.Contract.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Backend.Modules.Orders.Contract.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Backend.Modules.Shipments.Contract.Shipment", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
