name: Release

on:
  push:
    tags:
      - 'v**'

jobs:

  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        if: ${{ !env.ACT }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        if: ${{ !env.ACT }}
        run: dotnet restore

      - name: Build
        if: ${{ !env.ACT }}
        run: dotnet build --no-restore

  changelog:
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
      version: ${{ steps.git-cliff.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
          
  release:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    needs:
      - changelog
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get branch name
        id: branch_name
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref $GITHUB_SHA)
          echo $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "$BRANCH_NAME" >> $GITHUB_STEP_SUMMARY
      - name: Create Release
        if: ${{ !env.ACT && steps.branch_name.outputs.BRANCH_NAME != '' }}
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: ${{ needs.changelog.outputs.release_body }}
          name: "Версия ${{ needs.changelog.outputs.version }}"
          prerelease: ${{ steps.branch_name.outputs.BRANCH_NAME != 'master' }}
          latest: ${{ steps.branch_name.outputs.BRANCH_NAME == 'master' }}